config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :managers, controllers: { registrations: "managers/registrations", invitations: 'managers/invitations' }

  devise_scope :manager do
    post '/managers/invitation/:id/reinvite', to: 'managers/invitations#reinvite', as: :manager_invite
  end

  devise_for :users, controllers: { registrations: "users/registrations" }

  namespace :manager do
    resources :reports
    resources :expenses
    resources :projects do
      resources :tasks
      resources :invoices
    end
  end

  namespace :user do
    resources :projects do
      resources :tasks
    end
  end

  root "pages#index"
end

app/models/manager.rb
class Manager < ApplicationRecord
  has_many :manager_projects
  has_many :projects, through: :manager_projects
  has_many :tasks, as: :taskable
  has_many :expenses, as: :expenseable
  has_many :invited_managers, -> { where invited_by_type: "Manager" }, class_name: "Manager", foreign_key: "invited_by_id"
  has_one_attached :image
  validate :user_image?

  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :invitable

  delegate :invitation_not_accepted, to: :invited_managers, allow_nil: true, prefix: true
  delegate :invitation_accepted, to: :invited_managers, allow_nil: true, prefix: true

  def full_name
    "#{first_name} #{last_name}"
  end

  def invitation_status
    return "Not applicable" if invitation_accepted_at.nil? && invited_by_id.nil?
    return "Accepted" if invitation_accepted_at?
    "Pending"
  end

  private
    def user_image?
      errors.add(:base, 'Please upload your image.') unless image.attached?
    end
end

app/models/task.rb
class Task < ApplicationRecord
  scope :bill_able, -> { where(bill_able: true) }
  scope :filter_on, -> (date_range) { joins(:time_slots).where("start_time >= ? and end_time <= ?", date_range.formatted_start_time, date_range.formatted_end_time).uniq }

  has_many :task_reports
  has_many :reports, through: :task_reports

  belongs_to :taskable, polymorphic: true
  belongs_to :project
  has_many :time_slots, dependent: :destroy

  delegate :hour_cost, to: :project, allow_nil: true

  accepts_nested_attributes_for :time_slots, reject_if: :all_blank, allow_destroy: true

  validates_uniqueness_of :title

  def total_hours
    time_slots.collect(&:hours).sum
  end

  def price
    total_hours * hour_cost
  end
end

app/controllers/manager/expenses_controller.rb
class Manager::ExpensesController < ApplicationController
  before_action :set_expense, only: [:edit, :show, :update, :destroy]
  before_action :set_form_data, only: [:new, :edit, :update, :create]

  def index
    @expenses = Expense.all
  end

  def new
    @expense = Expense.new
  end

  def show
  end

  def edit
  end

  def create
    @expense = Expense.new(expense_params)
    if @expense.save
      redirect_to manager_expenses_path notice: 'Expense was created successfully.'
    else
      render :new
    end
  end

  def update
    if @expense.update(expense_params)
      redirect_to manager_expenses_path, notice: 'Expense was updated successfully.'
    else
      render :edit
    end
  end

  def destroy
    @expense.destroy
    redirect_to manager_expenses_path alert: 'Expense was destroyed successfully.'
  end

  private
    def expense_params
      params.require(:expense).permit(:recurring_expense, :title, :amount, :date, :expenseable_type, :expenseable_id, :expense_type, :manager_id)
    end

    def set_expense
      @expense = Expense.find(params[:id])
    end

    def set_form_data
      @expenseables = (User.all + Manager.all).collect { |expenseable| [expenseable.full_name.concat(" - #{expenseable.class}"), expenseable.id, { data_type: expenseable.class } ] }
      @expense_types = Expense.expense_types.keys
    end

end

app/controllers/manager/invoices_controller.rb
class Manager::InvoicesController < ApplicationController
  before_action :set_project
  before_action :set_invoice, only: [:show, :edit, :destroy, :update]

  def index
    @invoices = @project.invoices
  end

  def new
    date_range = DateRange.new(invoice_params[:start_time], invoice_params[:end_time]) if params[:invoice].present?
    if params[:invoice].present? && date_range.valid_range?
      @tasks = @project.tasks.bill_able.filter_on date_range
      @invoice = @project.invoices.build(per_hour_rate: @project.hour_cost,
        total_hours: @project.total_hours_for(@tasks),
        start_time: invoice_params[:start_time],
        end_time: invoice_params[:end_time])
    else
      @invoice = @project.invoices.build
    end
  end

  def show
  end

  def edit
  end

  def create
    @invoice =  @project.invoices.build(invoice_params)
    if @invoice.save
      redirect_to manager_project_invoices_path(@project), notice: 'Invoice was created successfully.'
    else
      render :new
    end
  end

  def update
    if @invoice.update(invoice_params)
      redirect_to manager_project_invoices_path(@project), notice: 'Invoice was updated successfully.'
    else
      render :edit
    end
  end

  def destroy
    if @invoice.destroy
      redirect_to manager_project_invoices_path(@project)
    else
      redirect_to manager_project_invoices_path(@project), alert: 'Something went wrong'
    end
  end

  private
    def invoice_params
      params.require(:invoice).permit(:per_hour_rate, :total_hours, :start_time, :end_time, :project_id)
    end

    def set_project
      @project = Project.find(params[:project_id])
    end

    def set_invoice
      @invoice = @project.invoices.find(params[:id])
    end

end

app/controllers/manager/projects_controller.rb
class Manager::ProjectsController < ApplicationController
  before_action :authenticate_manager!
  before_action :set_project, only: [:edit, :show, :update, :destroy]
  before_action :authorize_user, only: [:edit, :update, :destroy]
  before_action :users_list, only: [:new, :edit, :update, :create]

  def index
    @search = current_manager.projects.search(params[:q])
    @projects = @search.result
  end

  def new
    @project = Project.new
    @project.employee_projects.build
  end

  def show
  end

  def edit
    @project.employee_projects.build unless @project.employee_projects.present?
  end

  def create
    @project = Project.new(project_params.merge(manager_projects_attributes: [manager_id: current_manager.id]))

    if @project.save
      redirect_to manager_project_path(@project)
    else
      render :new
    end
  end

  def update
    if @project.update(project_params)
      redirect_to manager_project_path(@project)
    else
      render :edit
    end
  end

  def destroy
    if @project.destroy
      redirect_to manager_projects_path
    else
      redirect_to manager_projects_path, alert: 'Something went wrong'
    end
  end

  private
    def project_params
      params.require(:project).permit(:title, :discription, :hour_cost, employee_projects_attributes: [:id, :user_id, :_destroy])
    end

    def set_project
      @project = Project.find(params[:id])
    end

    def users_list
      @users = User.all.collect { |user| [user.full_name, user.id] }
    end

    def authorize_user
      if ManagerProject.where(project_id: params[:id], manager_id: current_manager.id).blank?
        redirect_to manager_projects_path, alert: 'You are not authorized for this action'
      end
    end
end

app/controllers/manager/reports_controller.rb
class Manager::ReportsController < ApplicationController
  before_action :set_report, only: [:show, :update, :destroy]

  def index
    @reports = Report.all
  end

  def new
    date_range = DateRange.new(report_params[:start_time], report_params[:end_time]) if params[:report].present?

    if params[:report].present? && date_range.valid_range?
      @report = Report.new(start_time: report_params[:start_time], end_time: report_params[:end_time])
      @report.tasks = @tasks = Task.bill_able.filter_on date_range
      @report.expenses = @expenses = Expense.filter_on_dates(report_params[:start_time], report_params[:end_time])
    else
      @report = Report.new
    end
  end

  def show
    @tasks = @report.tasks
    @expenses = @report.expenses
  end

  def create
    @report =  Report.new(report_params)
    if @report.save
      redirect_to manager_reports_path, notice: 'Report was created successfully.'
    else
      render :new
    end
  end

  def destroy
    @report.destroy
    redirect_to manager_reports_path alert: 'Report was destroyed successfully.'
  end

  private
    def report_params
      params.require(:report).permit(:total_income, :total_expense, :start_time, :end_time, expense_reports_attributes: [:expense_id], task_reports_attributes: [:task_id])
    end

    def set_report
      @report = Report.find(params[:id])
    end
end

app/controllers/manager/tasks_controller.rb
class Manager::TasksController < ApplicationController
  before_action :set_project
  before_action :set_task, only: [:show, :edit, :destroy, :update]

  def index
    @tasks = @project.tasks
  end

  def new
    @task = Task.new
    @task.time_slots.build
  end

  def show
  end

  def edit
    @task.time_slots.build unless @task.time_slots.present?
  end

  def create
    @task = current_manager.tasks.new(task_params.merge(project: @project))
    if @task.save
      redirect_to manager_project_tasks_path(@project)
    else
      render :new
    end
  end

  def update
    if @task.update(task_params)
      redirect_to manager_project_tasks_path(@project)
    else
      render :edit
    end
  end

  def destroy
    if @task.destroy
      redirect_to manager_project_tasks_path(@project)
    else
      redirect_to manager_project_tasks_path(@project), alert: 'Something went wrong'
    end
  end

  private
    def task_params
      params.require(:task).permit(:title, :discription, :bill_able, time_slots_attributes: [:id, :start_time, :end_time, :_destroy])
    end

    def set_project
      @project = Project.find(params[:project_id])
    end

    def set_task
      @task = @project.tasks.find(params[:id])
    end
end

app/controllers/managers/invitations_controller.rb
class Managers::InvitationsController < Devise::InvitationsController
  before_action :configure_permitted_parameters, if: :devise_controller?

  def new
    @pending_invitations = current_manager.invited_managers_invitation_not_accepted
    @accepted_invitations = current_manager.invited_managers_invitation_accepted
    super
  end

  def create
    self.resource = invite_resource
    resource_invited = resource.errors.empty?

    yield resource if block_given?

    flash.now[:notice] = "Invitation was sent successfully" if resource_invited
  end

  def reinvite
    @manager = Manager.find(params[:id])
    @manager.invite! { |manager| manager.invitations_count += 1  }
    flash.now[:notice] = "Invitation was sent successfully"
  end

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:accept_invitation)
    end

    def update_resource_params
      params.require(:manager).permit(:invitation_token, :first_name, :last_name, :password, :password_confirmation, :image)
    end

  private
    def invite_resource
      Manager.invite!({email: params[:manager][:email]}, current_manager)
    end
end

app/controllers/managers/registrations_controller.rb
class Managers::RegistrationsController < Devise::RegistrationsController
  protected
    def update_resource(resource, params)
      resource.update_with_password(sign_up_edit_params)
    end
  private
    def sign_up_edit_params
      params.require(:manager).permit(:first_name, :last_name, :password, :password_confirmation, :current_password, :email, :image)
    end
    def sign_up_params
      params.require(:manager).permit(:first_name, :last_name, :email, :password, :password_confirmation, :image)
    end
end

app/controllers/user/tasks_controller.rb
class User::TasksController < ApplicationController
  before_action :set_project
  before_action :set_task, only: [:show, :edit, :destroy, :update]

  def index
    @tasks = current_user.tasks.where(project_id: @project)
  end

  def new
    @task = Task.new
    @task.time_slots.build
  end

  def show
  end

  def edit
    @task.time_slots.build unless @task.time_slots.present?
  end

  def create
    @task = current_user.tasks.new(task_params.merge(project: @project))
    if @task.save
      redirect_to user_project_tasks_path(@project, @task)
    else
      render :new
    end
  end

  def update
    if @task.update(task_params)
      redirect_to user_project_tasks_path(@project)
    else
      render :edit
    end
  end

  def destroy
    if @task.destroy
      redirect_to user_project_tasks_path(@project)
    else
      redirect_to user_project_tasks_path(@project), alert: 'Something went wrong'
    end
  end

  private
    def task_params
      params.require(:task).permit(:title, :discription, :bill_able, time_slots_attributes: [:id, :start_time, :end_time, :_destroy])
    end

    def set_project
      @project = current_user.projects.find(params[:project_id])
    end

    def set_task
      @task = current_user.tasks.find(params[:id])
    end
end

app/helpers/manager/invoices_helper.rb
module Manager::InvoicesHelper
  def total_amount per_hour_rate, total_hours
    per_hour_rate * total_hours if per_hour_rate.present? && total_hours.present?
  end
end

app/views/manager/tasks/_form.html.erb
<%= form_for [:manager, project, task] do |f| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(task.errors.count, "error") %> prohibited
        this task from being saved:
      </h2>

      <ul>
        <% task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :discription %><br>
    <%= f.text_area :discription, class: "form-control" %>
  </div>

  <div class="checkbox">
    <label>
      <%= f.check_box :bill_able %> Bill able
    </label>
  </div>

  <div id='time_slots'>
    <%= f.fields_for :time_slots do |time_slot| %>
      <%= render 'time_slots_fields', f: time_slot %>
    <% end %>
    <div>
      <%= link_to_add_association 'add time', f, :time_slots, partial: 'time_slots_fields' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.submit class: 'form-control btn btn-success' %>
  </div>
<% end %>

app/views/manager/tasks/_task.html.erb
<tbody>
  <tr>
    <td><%= task.title %></td>
    <td><%= task.discription %></td>
    <td><%= task.bill_able %></td>
    <td>
      <%= link_to 'Show', manager_project_task_path(task.project, task) %> |
      <%= link_to 'Edit', edit_manager_project_task_path(task.project, task) %> |
      <%= link_to 'Destroy', manager_project_task_path(task.project, task), method: :delete, data: { confirm: 'Are you sure?' } %>
    </td>
  </tr>
</tbody>

app/views/manager/tasks/_time_slots_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <p>
      <%= f.label :start_time %><br>
      <%= f.datetime_select :start_time %>
    </p>

    <p>
      <%= f.label :end_time %><br>
      <%= f.datetime_select :end_time, class: "form-control" %>
    </p>
  </div>

  <%= link_to_remove_association "remove", f %>
</div>

app/views/manager/tasks/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-4 col-sm-offset-4">
      <div class="light-well">
        <h2 class="page-header text-center">Edit task</h2>

        <%= render 'form', task: @task, project: @project %>

        <%= link_to 'Back', manager_project_tasks_path(@project) %>
    </div>
  </div>
</div>

app/views/manager/tasks/index.html.erb
<h1>Listing tasks</h1>

<%= link_to 'New task', new_manager_project_task_path(@project) %>
<table class="table table-sm">
  <tr>
    <th>Title</th>
    <th>Discription</th>
    <th>Bill able</th>
    <th>CRUD</th>
  </tr>

   <%= render @tasks %>
</table>

app/views/manager/tasks/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-4 col-sm-offset-4">
      <div class="light-well">
        <h2 class="page-header text-center">New Task</h2>

        <%= render 'form', task: @task, project: @project %>

        <%= link_to 'Back', manager_project_tasks_path %>
      </div>
    </div>
  </div>
</div>

app/views/manager/tasks/show.html.erb
<div class="container">
  <div class="panel panel-default">
    <div class="panel-body">
      <p>
        <strong>Title:</strong>
        <%= @task.title %>
      </p>

      <p>
        <strong>Discription:</strong>
        <%= @task.discription %>
      </p>

      <p>
        <strong>Bill able:</strong>
        <%= @task.bill_able %>
      </p>
    </div>
    <div class="panel-footer">
      <%= link_to 'Edit', edit_manager_project_task_path(@project, @task) %> |
      <%= link_to 'Back', manager_project_tasks_path(@project, @task) %>
    </div>
  </div>
</div>