config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :managers, controllers: { registrations: "managers/registrations", invitations: 'managers/invitations' }

  devise_scope :manager do
    post '/managers/invitation/:id/reinvite', to: 'managers/invitations#reinvite', as: :manager_invite
  end

  devise_for :users, controllers: { registrations: "users/registrations" }

  namespace :manager do
    resources :reports
    resources :expenses
    resources :projects do
      resources :tasks
      resources :invoices
    end
  end

  namespace :user do
    resources :projects do
      resources :tasks
    end
  end

  root "pages#index"
end

app/models/task.rb
class Task < ApplicationRecord
  scope :bill_able, -> { where(bill_able: true) }
  scope :filter_on, -> (date_range) { joins(:time_slots).where("start_time >= ? and end_time <= ?", date_range.formatted_start_time, date_range.formatted_end_time).uniq }

  has_many :task_reports
  has_many :reports, through: :task_reports

  belongs_to :taskable, polymorphic: true
  belongs_to :project
  has_many :time_slots, dependent: :destroy

  delegate :hour_cost, to: :project, allow_nil: true

  accepts_nested_attributes_for :time_slots, reject_if: :all_blank, allow_destroy: true

  validates_uniqueness_of :title

  def total_hours
    time_slots.collect(&:hours).sum
  end

  def price
    total_hours * hour_cost
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :employee_projects
  has_many :projects, through: :employee_projects
  has_many :tasks, as: :taskable
  has_many :expenses, as: :expenseable
  has_one_attached :image
  validate :user_image?

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def full_name
    "#{first_name} #{last_name}"
  end

  private
    def user_image?
      errors.add(:base, 'Please upload your image.') unless image.attached?
    end
end

app/controllers/manager/tasks_controller.rb
class Manager::TasksController < ApplicationController
  before_action :set_project
  before_action :set_task, only: [:show, :edit, :destroy, :update]

  def index
    @tasks = @project.tasks
  end

  def new
    @task = Task.new
    @task.time_slots.build
  end

  def show
  end

  def edit
    @task.time_slots.build unless @task.time_slots.present?
  end

  def create
    @task = current_manager.tasks.new(task_params.merge(project: @project))
    if @task.save
      redirect_to manager_project_tasks_path(@project)
    else
      render :new
    end
  end

  def update
    if @task.update(task_params)
      redirect_to manager_project_tasks_path(@project)
    else
      render :edit
    end
  end

  def destroy
    if @task.destroy
      redirect_to manager_project_tasks_path(@project)
    else
      redirect_to manager_project_tasks_path(@project), alert: 'Something went wrong'
    end
  end

  private
    def task_params
      params.require(:task).permit(:title, :discription, :bill_able, time_slots_attributes: [:id, :start_time, :end_time, :_destroy])
    end

    def set_project
      @project = Project.find(params[:project_id])
    end

    def set_task
      @task = @project.tasks.find(params[:id])
    end
end

app/controllers/user/projects_controller.rb
class User::ProjectsController < ApplicationController
  before_action :authenticate_user!

  def index
    @projects = current_user.projects
  end

  def show
     @project = Project.find(params[:id])
  end
end

app/controllers/user/tasks_controller.rb
class User::TasksController < ApplicationController
  before_action :set_project
  before_action :set_task, only: [:show, :edit, :destroy, :update]

  def index
    @tasks = current_user.tasks.where(project_id: @project)
  end

  def new
    @task = Task.new
    @task.time_slots.build
  end

  def show
  end

  def edit
    @task.time_slots.build unless @task.time_slots.present?
  end

  def create
    @task = current_user.tasks.new(task_params.merge(project: @project))
    if @task.save
      redirect_to user_project_tasks_path(@project, @task)
    else
      render :new
    end
  end

  def update
    if @task.update(task_params)
      redirect_to user_project_tasks_path(@project)
    else
      render :edit
    end
  end

  def destroy
    if @task.destroy
      redirect_to user_project_tasks_path(@project)
    else
      redirect_to user_project_tasks_path(@project), alert: 'Something went wrong'
    end
  end

  private
    def task_params
      params.require(:task).permit(:title, :discription, :bill_able, time_slots_attributes: [:id, :start_time, :end_time, :_destroy])
    end

    def set_project
      @project = current_user.projects.find(params[:project_id])
    end

    def set_task
      @task = current_user.tasks.find(params[:id])
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  protected
    def update_resource(resource, params)
      resource.update_with_password(sign_up_edit_params)
    end
  private
    def sign_up_edit_params
      params.require(:user).permit(:first_name, :last_name, :password, :password_confirmation, :current_password, :email, :image)
    end
    def sign_up_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :image)
    end
end

app/views/user/tasks/_form.html.erb
<%= form_for [:user, project, task] do |f| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(task.errors.count, "error") %> prohibited
        this task from being saved:
      </h2>

      <ul>
        <% task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :discription %><br>
    <%= f.text_area :discription, class: "form-control" %>
  </div>

  <div class="checkbox">
    <label><%= f.check_box :bill_able %> Bill able</label>
  </div>

  <div id='time_slots'>
    <%= f.fields_for :time_slots do |time_slot| %>
      <%= render 'time_slots_fields', f: time_slot %>
    <% end %>
    <div>
      <%= link_to_add_association 'add time', f, :time_slots, partial: 'time_slots_fields' %>
    </div>
  </div>

  <%= f.submit class: 'form-control btn btn-success' %>
<% end %>

app/views/user/tasks/_task.html.erb
<tbody>
  <tr>
    <td><%= task.title %></td>
    <td><%= task.discription %></td>
    <td>
     <%= link_to 'Show', user_project_task_path(task.project, task) %> |
     <%= link_to 'Edit', edit_user_project_task_path(task.project, task) %> |
     <%= link_to 'Destroy', user_project_task_path(task.project, task), method: :delete, data: { confirm: 'Are you sure?' } %>
    </td>
  </tr>
</tbody>

app/views/user/tasks/_time_slots_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <p>
      <%= f.label :start_time %><br>
      <%= f.datetime_select :start_time %>
    </p>

    <p>
      <%= f.label :end_time %><br>
      <%= f.datetime_select :end_time %>
    </p>
  </div>

  <%= link_to_remove_association "remove", f %>
</div>

app/views/user/tasks/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-4 col-sm-offset-4">
      <div class="light-well">
        <h2 class="page-header text-center">Edit task</h2>

        <%= render 'form', task: @task, project: @project %>

        <%= link_to 'Back', user_project_tasks_path %>
      </div>
    </div>
  </div>
</div>

app/views/user/tasks/index.html.erb
<h1>Listing tasks</h1>

<%= link_to 'New task', new_user_project_task_path(@project) %>
<table class="table table-sm">
  <tr>
    <th>Title</th>
    <th>Discription</th>
    <th>CRUD</th>
  </tr>

   <%= render @tasks %>
</table>

app/views/user/tasks/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-4 col-sm-offset-4">
      <div class="light-well">
        <h2 class="page-header text-center">New task</h2>

        <%= render 'form', task: @task, project: @project %>

        <%= link_to 'Back', user_project_tasks_path %>
      </div>
    </div>
  </div>
</div>

app/views/user/tasks/show.html.erb
<div class="container">
  <div class="panel panel-default">
    <div class="panel-body">
      <p>
        <strong>Title:</strong>
        <%= @task.title %>
      </p>

      <p>
        <strong>Discription:</strong>
        <%= @task.discription %>
      </p>
    </div>
    <div class="panel-footer">
      <%= link_to 'Edit', edit_user_project_task_path(@project, @task) %> |
      <%= link_to 'Back', user_project_tasks_path(@project, @task) %>
    </div>
  </div>
</div>