config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :managers, controllers: { registrations: "managers/registrations", invitations: 'managers/invitations' }

  devise_scope :manager do
    post '/managers/invitation/:id/reinvite', to: 'managers/invitations#reinvite', as: :manager_invite
  end

  devise_for :users, controllers: { registrations: "users/registrations" }

  namespace :manager do
    resources :reports
    resources :expenses
    resources :projects do
      resources :tasks
      resources :invoices
    end
  end

  namespace :user do
    resources :projects do
      resources :tasks
    end
  end

  root "pages#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee_project.rb
class EmployeeProject < ApplicationRecord
  belongs_to :user
  belongs_to :project

  validates :user_id, uniqueness: { scope: :project_id }
end

app/models/expense.rb
class Expense < ApplicationRecord
  scope :filter_on_dates, -> (start_time, end_time) { where("date >= ? and date <= ?", start_time.to_datetime, end_time.to_datetime.end_of_day) }
  has_many :expense_reports
  has_many :reports, through: :expense_reports

  belongs_to :expenseable, polymorphic: true , optional: true

  validates :title, :amount, :expense_type, :date, presence: true

  enum expense_type: {
    salary: 0,
    bill: 1,
    rent: 2,
    maintenence: 3,
    others: 4,
  }
end

app/models/expense_report.rb
class ExpenseReport < ApplicationRecord
  belongs_to :report
  belongs_to :expense
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :project
end

app/models/manager.rb
class Manager < ApplicationRecord
  has_many :manager_projects
  has_many :projects, through: :manager_projects
  has_many :tasks, as: :taskable
  has_many :expenses, as: :expenseable
  has_many :invited_managers, -> { where invited_by_type: "Manager" }, class_name: "Manager", foreign_key: "invited_by_id"
  has_one_attached :image
  validate :user_image?

  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :invitable

  delegate :invitation_not_accepted, to: :invited_managers, allow_nil: true, prefix: true
  delegate :invitation_accepted, to: :invited_managers, allow_nil: true, prefix: true

  def full_name
    "#{first_name} #{last_name}"
  end

  def invitation_status
    return "Not applicable" if invitation_accepted_at.nil? && invited_by_id.nil?
    return "Accepted" if invitation_accepted_at?
    "Pending"
  end

  private
    def user_image?
      errors.add(:base, 'Please upload your image.') unless image.attached?
    end
end

app/models/manager_project.rb
class ManagerProject < ApplicationRecord
  belongs_to :manager
  belongs_to :project
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :manager_projects, dependent: :destroy
  has_many :managers, through: :manager_projects

  has_many :employee_projects, dependent: :destroy
  has_many :users, through: :employee_projects
  has_many :tasks, dependent: :destroy
  has_many :invoices, dependent: :destroy

  validates :title, presence: true

  accepts_nested_attributes_for :manager_projects
  accepts_nested_attributes_for :employee_projects, reject_if: :all_blank, allow_destroy: true

  def total_hours_for tasks
    tasks.collect(&:total_hours).sum
  end

end

app/models/report.rb
class Report < ApplicationRecord
  has_many :expense_reports, dependent: :destroy
  has_many :expenses, through: :expense_reports

  has_many :task_reports, dependent: :destroy
  has_many :tasks, through: :task_reports

  accepts_nested_attributes_for :expense_reports
  accepts_nested_attributes_for :task_reports, reject_if: :all_blank, allow_destroy: true

  def total_incomes tasks
    tasks.collect(&:price).sum
  end

  def total_expenses expenses
    expenses.collect(&:amount).sum
  end
end

app/models/task.rb
class Task < ApplicationRecord
  scope :bill_able, -> { where(bill_able: true) }
  scope :filter_on, -> (date_range) { joins(:time_slots).where("start_time >= ? and end_time <= ?", date_range.formatted_start_time, date_range.formatted_end_time).uniq }

  has_many :task_reports
  has_many :reports, through: :task_reports

  belongs_to :taskable, polymorphic: true
  belongs_to :project
  has_many :time_slots, dependent: :destroy

  delegate :hour_cost, to: :project, allow_nil: true

  accepts_nested_attributes_for :time_slots, reject_if: :all_blank, allow_destroy: true

  validates_uniqueness_of :title

  def total_hours
    time_slots.collect(&:hours).sum
  end

  def price
    total_hours * hour_cost
  end
end

app/models/task_report.rb
class TaskReport < ApplicationRecord
  belongs_to :report
  belongs_to :task
end

app/models/time_slot.rb
class TimeSlot < ApplicationRecord
  belongs_to :task

  def hours
    (end_time - start_time).to_i / 3600
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :employee_projects
  has_many :projects, through: :employee_projects
  has_many :tasks, as: :taskable
  has_many :expenses, as: :expenseable
  has_one_attached :image
  validate :user_image?

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def full_name
    "#{first_name} #{last_name}"
  end

  private
    def user_image?
      errors.add(:base, 'Please upload your image.') unless image.attached?
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/user/tasks_controller.rb
class User::TasksController < ApplicationController
  before_action :set_project
  before_action :set_task, only: [:show, :edit, :destroy, :update]

  def index
    @tasks = current_user.tasks.where(project_id: @project)
  end

  def new
    @task = Task.new
    @task.time_slots.build
  end

  def show
  end

  def edit
    @task.time_slots.build unless @task.time_slots.present?
  end

  def create
    @task = current_user.tasks.new(task_params.merge(project: @project))
    if @task.save
      redirect_to user_project_tasks_path(@project, @task)
    else
      render :new
    end
  end

  def update
    if @task.update(task_params)
      redirect_to user_project_tasks_path(@project)
    else
      render :edit
    end
  end

  def destroy
    if @task.destroy
      redirect_to user_project_tasks_path(@project)
    else
      redirect_to user_project_tasks_path(@project), alert: 'Something went wrong'
    end
  end

  private
    def task_params
      params.require(:task).permit(:title, :discription, :bill_able, time_slots_attributes: [:id, :start_time, :end_time, :_destroy])
    end

    def set_project
      @project = current_user.projects.find(params[:project_id])
    end

    def set_task
      @task = current_user.tasks.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class_name(name)
    return 'success' if name == 'notice'
    return 'danger' if name == 'alert'
  end

  def date_formate date
    date.strftime("%m/%d/%Y")
  end

  def date_time_formate date
    date.strftime("%d/%m/%Y %I:%M %p")
  end
end

app/helpers/image_helper.rb
module ImageHelper
  def render_image_tag(image)
    image_tag(url_for(image)) if image.attached?
  end
end

app/helpers/manager/invoices_helper.rb
module Manager::InvoicesHelper
  def total_amount per_hour_rate, total_hours
    per_hour_rate * total_hours if per_hour_rate.present? && total_hours.present?
  end
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <%- if user_signed_in? %>
      <ul class="nav navbar-nav">
        <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
        <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
        <li><%= link_to 'Project', user_projects_path %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <%= image_tag(current_user.image, class: "img-thumbnail", size: "80x80") %>
      </ul>
    <% elsif manager_signed_in? %>
      <ul class="nav navbar-nav">
        <li><%= link_to 'Sign out', destroy_manager_session_path, method: :delete %></li>
        <li><%= link_to 'Edit Profile', edit_manager_registration_path %></li>
        <li><%= link_to 'Project', manager_projects_path %></li>
        <li><%= link_to 'Expenses', manager_expenses_path %></li>
        <li><%= link_to 'Financial Reports', manager_reports_path %></li>
        <li><%= link_to 'Send invitations', new_manager_invitation_path %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <%= image_tag(current_manager.image, class: "img-thumbnail", size: "80x80") %>
      </ul>
    <% else %>
      <ul class="nav navbar-nav"> <li><%= link_to 'Sign in as Manager', new_manager_session_path %></li></ul>
      <ul class="nav navbar-nav"> <li><%= link_to 'Sign in as User', new_user_session_path %></li></ul>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TrackingSystem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <%= render 'shared/flash' %>

    <div class="container">
      <%= yield %>
    </div>

    <script type="text/javascript">
      <%= yield :js_init %>
    </script>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(resource.errors.count, "error") %> prohibited
      this expense from being saved:
    </h2>

    <ul>
      <% resource.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<div id="flash_message">
  <% flash.each do |message_type, message| %>
    <div class="alert text-center alert-<%= flash_class_name(message_type) %> alert-dismissable">
      <span><%= message %></span>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
</div>